SSWConsulting/SSW.Rules.GPT

- SSW.Rules.GPT.sln
- src/Application/Application.csproj
- src/Application/DependencyInjection.cs
- src/Application/Services/EmbeddingNeighboursService.cs
- src/Application/Services/MessageHandler.cs
- src/Application/Services/RelevantRulesService.cs
- src/Domain/Domain.csproj
- src/Domain/Entities/MatchRulesResult.cs
- src/Infrastructure/DependencyInjection.cs
- src/Infrastructure/Infrastructure.csproj
- src/WebAPI/DependencyInjection.cs
- src/WebAPI/SignalR/RulesHub.cs
- src/WebAPI/SignalR/SignalRHubFilter.cs
- src/WebAPI/WebAPI.csproj
- src/WebUI/Models/AvailableGptModels.cs
- src/WebUI/Models/DataState.cs
- tests/Application.IntegrationTests/Application.IntegrationTests.csproj
- tests/Application.IntegrationTests/Services/RelevantRulesServiceTests.cs
- tests/Application.IntegrationTests/Usings.cs
Closes #40 
Refactored SignalR Hub and added integration test for similar rules based on user input
> 40 add integration tests for embedding

- src/WebUI/Services/MarkdigPipelineService.cs
Closes #69 
* Added option to markdig autolinks to have them open in a new window
* Set default behaviour of `www.` addresses to be https
> ✨Added Link Open in New Window

- src/WebUI/Components/RulesBotChat.razor
Closes #47 
Added a margin to the bottom of the most recent message whilst waiting for a response to complete.
> ❌ UI - Cancel Button Over GPT Answer

- src/WebUI/Classes/DarkModePreference.cs
- src/WebUI/Classes/ThemePreference.cs
- src/WebUI/Program.cs
- src/WebUI/Shared/MainLayout.razor
- src/WebUI/WebUI.csproj
- src/WebUI/_Imports.razor
Closes #80 
Dark mode preference is now stored in localStorage.
The app can also now detect system preference.
> ♻️ 80 - Store dark mode preference in localStorage

- .github/pull_request_template.md
- Update the PR template based on the template repo
> 🧑‍💻 DevEx - Improve PR template

- src/Application/Services/OpenAiServiceFactory.cs
- src/Infrastructure/DependencyInjection.cs
* Added missing using statement
* Added better null safety for initialising Azure OpenAI service
Closes #92
> 🐛 Bug - Fixed Broken Deployment

- src/Application/Services/OpenAiServiceFactory.cs
- src/Infrastructure/DependencyInjection.cs
- tests/Application.IntegrationTests/Services/RelevantRulesServiceTests.cs
* Fixed integration tests to work with factory
Related to #92
> 🐛 Bug - Broken Deployment

- src/WebUI/wwwroot/index.html
Add meta tags to the page so that it is more easily googleable and provides better information to web crawlers.
Related to #85 
**Figure: Current result on Google**
**Figure: Meta tags on current production deployment**
**Figure: Meta tags on staging deployment**
> Add meta tags

- src/Application/Services/MessageHandler.cs
Related to #96 
Update the system prompt to explicitly require numbered lists when listing anything.
**Figure: Lists before the change**
**Figure: Lists after the change**
> 🎨 Use standard lists

- .gitignore
- README.md
- src/WebAPI/appsettings.Development.json
- src/WebAPI/appsettings.json
- src/WebUI/Properties/launchSettings.json
- src/WebUI/wwwroot/appsettings.json
Related to #122 
Remove secrets from appsettings.json into secrets.json and update the readme.
> 👷 Clean up secrets and connection strings

- src/WebAPI/SignalR/IRulesClient.cs
- src/WebAPI/SignalR/RulesHub.cs
- src/WebUI/Classes/ChatLinkedList.cs
- src/WebUI/Classes/ChatLinkedListItem.cs
- src/WebUI/Components/ChatItem.razor
- src/WebUI/Components/Dialogs/ApiKeyDialog.razor
- src/WebUI/Components/RulesBotChat.razor.cs
- src/WebUI/Enums/AvailableGptModels.cs
- src/WebUI/Enums/Direction.cs
- src/WebUI/Enums/StatusHubConnectionState.cs
- src/WebUI/Enums/ValidationState.cs
- src/WebUI/Program.cs
- src/WebUI/Services/ApiKeyValidationService.cs
- src/WebUI/Services/MarkdigPipelineService.cs
- src/WebUI/Services/NotifierService.cs
- src/WebUI/Services/UserService.cs
- src/WebUI/Shared/MainLayout.razor
- src/WebUI/SignalRClient.cs
Gives signed in users access to GPT-4.
Once you are signed in you will be automatically switched to GPT-4, but you can switch back in the API Key menu if you want to.
Also cleans up some files and removes some unused code.
Related to #102
> ✨ Identity Server - Give signed in users GPT-4 access

- src/WebUI/Shared/MainLayout.razor
Changes the behaviour of the logo/title in the header so clicking it returns the user to the homepage.
Related to #137
> 🐛 Fix header logo click behaviour

- .github/workflows/template-build-deploy.yml
- src/WebAPI/DependencyInjection.cs
- src/WebAPI/Program.cs
- src/WebAPI/appsettings.Development.json
- src/WebAPI/appsettings.json
Removes hardcoded URLs from code and prevents staging build being able to connect to prod and vice versa.
Related to #120
> ♻️ Remove hardcoded CORS URLs

- .github/workflows/main-build-deploy.yml
- .github/workflows/template-build-deploy.yml
Update deprecated Github Actions (Node 16)
> ⬆️ Update deprecated Github Actions

- src/Application/Services/ChatHistoryService.cs
- src/Application/Services/LeaderboardService.cs
- src/WebAPI/DependencyInjection.cs
- src/WebAPI/Program.cs
- src/WebAPI/Routes/ConversationHistoryRoutes.cs
- src/WebAPI/Routes/LeaderboardRoutes.cs
- src/WebAPI/SignalR/SignalRHubFilter.cs
> ♻️ Make db calls async

- .github/workflows/template-build-deploy.yml
- SSW.Rules.GPT.sln
- src/WebAPI/DependencyInjection.cs
- src/WebAPI/Program.cs
- src/WebAPI/WebAPI.csproj
> ✨ Database Health Check

- .github/bicep/main.bicep
> Restoring kv version

- .github/bicep/main.bicep
> ⬆️ Update Azure App Service .NET version

- src/WebAPI/DependencyInjection.cs
- src/WebAPI/Program.cs
- src/WebAPI/Routes/ConversationHistoryRoutes.cs
- src/WebAPI/Routes/LeaderboardRoutes.cs
- src/WebUI/RulesGptApiClients.cs
> 🐛 Fix CORS for SignalR

- src/Application/Application.csproj
- src/Application/Contracts/IOpenAiChatCompletionsService.cs
- src/Application/Services/ChatCompletionsService.cs
- src/Application/Services/MessageHandler.cs
- src/Application/Services/OpenAiServiceFactory.cs
- src/Application/Services/PruningService.cs
- src/Application/Services/RelevantRulesService.cs
- src/Application/Services/TokenService.cs
- src/Domain/Domain.csproj
- src/Infrastructure/DependencyInjection.cs
- src/Infrastructure/Infrastructure.csproj
- src/Infrastructure/Services/OpenAiChatCompletionsService.cs
- src/Infrastructure/Services/OpenAiEmbeddingService.cs
- src/Shared/AvailableGptModels.cs
- src/Shared/ChatLinkedListItem.cs
- src/Shared/ChatMessage.cs
- src/Shared/Shared.csproj
- src/WebAPI/SignalR/RulesHub.cs
- src/WebAPI/WebAPI.csproj
- src/WebUI/Components/RulesBotChat.razor
- src/WebUI/Models/DataState.cs
- src/WebUI/Services/ApiKeyValidationService.cs
- src/WebUI/Services/MessagingService.cs
- src/WebUI/SignalRClient.cs
- src/WebUI/WebUI.csproj
- src/WebUI/_Imports.razor
- tests/Application.IntegrationTests/Application.IntegrationTests.csproj
- tests/Application.IntegrationTests/Services/RelevantRulesServiceTests.cs
- tests/Application.UnitTests/Application.UnitTests.csproj
> ⬆️ Bump Package Versions

- src/WebAPI/Routes/ConversationHistoryRoutes.cs
> 🐛 Remove unused auth policy from endpoints

- src/WebUI/Components/Dialogs/AboutAppDialog.razor
- src/WebUI/Components/Dialogs/ApiKeyDialog.razor
- src/WebUI/Components/Dialogs/InstallInstructionDialog.razor
- src/WebUI/Shared/MainLayout.razor
- src/WebUI/WebUI.csproj
> ⬆️ Update Mudblazor

- Directory.Build.props
- SSW.Rules.GPT.sln
- src/Application/Application.csproj
- src/Application/Contracts/IOpenAiEmbeddingService.cs
- src/Application/Services/ChatCompletionsService.cs
- src/Application/Services/OpenAiServiceFactory.cs
- src/Application/Services/RelevantRulesService.cs
- src/Infrastructure/DependencyInjection.cs
- src/Infrastructure/Infrastructure.csproj
- src/Infrastructure/Services/OpenAiChatCompletionsService.cs
- src/Infrastructure/Services/OpenAiEmbeddingService.cs
- src/Infrastructure/Services/SemanticKernelService.cs
- src/Shared/ChatLinkedList.cs
- src/Shared/ChatLinkedListItem.cs
- src/Shared/ChatMessage.cs
- src/WebUI/Components/ChatItem.razor
- src/WebUI/Components/Dialogs/ApiKeyDialog.razor
- src/WebUI/Components/MultilineInput.razor
- src/WebUI/Components/RulesBotChat.razor
- src/WebUI/Models/DataState.cs
- src/WebUI/Program.cs
- src/WebUI/Services/UserService.cs
- src/WebUI/Shared/MainLayout.razor
- src/WebUI/SignalRClient.cs
- tests/Application.UnitTests/Application.UnitTests.csproj
- tests/Application.UnitTests/Usings.cs
> ♻️ Resolve Nullable Warnings + Enable Warnings as Errors

- .github/workflows/main-build-deploy.yml
- .github/workflows/stage-build-deploy.yml
- .github/workflows/template-build-deploy.yml
Related to Zendesk ticket: https://pdi-ssw.zendesk.com/agent/tickets/17177
Azure service principal secrets are about to expire - changing to federated credentials for better security & no more expiring secrets.
> Use Federated Credentials

- .github/workflows/template-build-deploy.yml
See: https://github.com/SSWConsulting/SSW.Rules.GPT/pull/184
I missed other places where Azure Login is used...
> Federated Credentials 2
